# Generated by Django 2.2.18 on 2021-04-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0085_add_publish_date_cvssv3_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='replicate_false_positive_across_product_type',
            field=models.BooleanField(default=False, help_text='Automatically mark the finding as false positive if the finding was marked as false positive in another product from the same product type.'),
        ),
    ]
