# Generated by Django 3.1.12 on 2021-07-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0113_endpoint_protocol'),
        ('dojo', '0091_auto_20210420_1748'),
    ]

    operations = [
    ]
