# Generated by Django 2.2.18 on 2021-07-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', 'local_0001_product_risk_acceptance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_settings',
            name='replicate_false_positive_across_product_type',
        ),
    ]
